### ISSUE TITLE
Errors when jacksheet numbers are over 256

### ISSUE THREAD

**Issue by mivade** [pennmem/bptools#19]
Example traceback:

```pytb
Traceback (most recent call last):
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/bin/ramulator-conf", line 11, in <module>
    load_entry_point('ramutils==2.1.10', 'console_scripts', 'ramulator-conf')()
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/ramutils/cli/expconf.py", line 196, in create_expconf
    use_classifier_excluded_leads=args.use_classifier_excluded_leads)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/ramutils/pipelines/ramulator_config.py", line 112, in make_ramulator_config
    use_common_reference).compute()
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/dask/compatibility.py", line 60, in reraise
    raise exc
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/ramutils/tasks/_wrapper.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/ramutils/tasks/odin.py", line 108, in generate_electrode_config
    ec.to_csv(csv_path)
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/bptools-1.3.0-py3.6.egg/bptools/odin/config.py", line 641, in to_csv
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/bptools-1.3.0-py3.6.egg/bptools/odin/config.py", line 595, in _export
  File "/home1/RAM_clinical/miniconda3/envs/ramutils/lib/python3.6/site-packages/bptools-1.3.0-py3.6.egg/bptools/odin/config.py", line 34, in _num_to_bank_label
KeyError: 4
```

Last few lines of `jacksheet.txt`:

```
220 RY14
221 RY15
222 RY16
223 ECG1
224 ECG2
258 DC09
259 DC10
```

**Comment by mivade** [comment]
We can either solve this by ignoring numbers that go above 256 or raise an error with a more informative message. The limitation is the ENS having up to 256 channels in total.
