### ISSUE TITLE
Standardizing labels still breaks Ramulator

### ISSUE THREAD

**Issue by mivade** [pennmem/bptools#9]
```pytb
Traceback (most recent call last):
  File "C:/Users/OdinUser/src/SYS3\rampy\ramulator\ramulator.py", line 1011, in load_experiment_config
    self.system_init()
  File "C:/Users/OdinUser/src/SYS3\rampy\ramulator\ramulator.py", line 1019, in system_init
    ret = self.init_experiment_runner()
  File "C:/Users/OdinUser/src/SYS3\rampy\ramulator\ramulator.py", line 400, in init_experiment_runner
    self.populate_electrode_table()
  File "C:/Users/OdinUser/src/SYS3\rampy\ramulator\ramulator.py", line 379, in populate_electrode_table
    self.configure_electrode_table(electrode_filename=electrode_filename, montage_filename=montage_filename)
  File "C:/Users/OdinUser/src/SYS3\rampy\ramulator\ramulator.py", line 798, in configure_electrode_table
    st = SeriesTransformation.create(electrode_filename, montage_file=montage_filename)
  File "c:\users\odinuser\src\bptools\bptools\transform.py", line 50, in create
    elec_conf = ElectrodeConfig(electrode_config_file)
  File "c:\users\odinuser\src\bptools\bptools\odin\config.py", line 256, in __init__
    self.read_config_file(filename)
  File "c:\users\odinuser\src\bptools\bptools\odin\config.py", line 425, in read_config_file
    contact.label = standardize_label(contact.label)
  File "c:\users\odinuser\src\bptools\bptools\util.py", line 59, in standardize_label
    if label[-2] == "0":
IndexError: string index out of range
```

**Comment by mivade** [comment]
@zduey, let's not enable standardization by default since it keeps breaking things.

**Comment by zduey** [comment]
Yeah, that makes sense. What was the input that caused this?

**Comment by mivade** [comment]
An Emory config file (1337)

On October 11, 2017 5:15:59 PM EDT, Zach Duey <notifications@github.com> wrote:
>Yeah, that makes sense. What was the input that caused this?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pennmem/bptools/issues/9#issuecomment-335950938

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mivade** [comment]
@zduey see commit 2508410. That test fails from standardization, so I marked it to be skipped.

**Comment by zduey** [comment]
I can't replicate this on my end. I'll snag you some time this morning to see if we can sort out what was going on.

**Comment by mivade** [comment]
Closing since this will now be disabled by default.
